export const studentList = [
  {
    id: 0,
    firstName: "Cédric",
    lastName: "NOYEL",
    email: "cedric.noyel@imt-atlantique.net",
    status: "Absent",
    classGroup: "front",
  },
  {
    id: 1,
    firstName: "Jordan",
    lastName: "GENEVE",
    email: "jodan.geneve@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 2,
    firstName: "Gaël",
    lastName: "BENAISSA",
    email: "gael.benaissa@imt-atlantique.net",
    status: "Absent",
    classGroup: "front",
  },
  {
    id: 3,
    firstName: "Mathis",
    lastName: "DELAUNAY",
    email: "mathis.delaunay@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 4,
    firstName: "Léa",
    lastName: "LOUESDON",
    email: "lea.louesdon@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 5,
    firstName: "Chloé",
    lastName: "MASONI",
    email: "chloe.masoni@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 6,
    firstName: "Gaëtan",
    lastName: "CEUTERICKX",
      email: "gaetan.ceuterickx@imt-atlantique.net",
    status: "En télétravail",
    classGroup: "front",
  },
  {
    id: 7,
    firstName: "Océane",
    lastName: "BERTHE",
    email: "oceeane.berthe@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 8,
    firstName: "Lucille",
    lastName: "GILLARD",
    email: "lucille.gillard@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 9,
    firstName: "Axel",
    lastName: "COUDRAY",
    email: "axel.coudray@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 10,
    firstName: "Xavier",
    lastName: "ALEMAN",
    email: "xavier.aleman@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 11,
    firstName: "Paul",
    lastName: "BAVAZZANO",
    email: "paul.bavazzano@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 12,
    firstName: "Robin",
    lastName: "CARREZ",
    email: "robin.carrez@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 13,
    firstName: "Emeric",
    lastName: "CHONIGBAUM",
    email: "emeric.chonigbaum@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 14,
    firstName: "Théo",
    lastName: "COUTAN",
    email: "theo.coutan@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 15,
    firstName: "Evrard-Nil",
    lastName: "DAILLET",
    email: "evrard-nil.daillet@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 16,
    firstName: "Ismaël",
    lastName: "ELKANTACH",
    email: "ismael.elkantack@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 17,
    firstName: "Maël",
    lastName: "GAONACH",
    email: "mael.gaonach@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 18,
    firstName: "Raphaël",
    lastName: "HASCOUET",
    email: "raphael.hascouet@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 19,
    firstName: "Thomas",
    lastName: "HERBELIN",
    email: "thomas.herbelin@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 20,
    firstName: "Marc",
    lastName: "LAMY",
    email: "marc.lamy@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 21,
    firstName: "Simon",
    lastName: "LEBARS",
    email: "simon.lebars@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 22,
    firstName: "Samy",
    lastName: "LEGALLOUDEC",
    email: "samy.legalloudec@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 23,
    firstName: "Florian",
    lastName: "LEMENN",
    email: "florian.lemenn@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 24,
    firstName: "Antoine",
    lastName: "OMOND",
    email: "antoine.omond@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 25,
    firstName: "Lucas",
    lastName: "PELEC",
    email: "lucas.pelec@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 26,
    firstName: "Javed",
    lastName: "SYEDKHASIM",
    email: "javed.syedkhasim@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 27,
    firstName: "Barthélémy",
    lastName: "TEK",
    email: "barthelemy.tek@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
  {
    id: 28,
    firstName: "Hoan-My",
    lastName: "Tran",
    email: "hoan-my.tran@imt-atlantique.net",
    status: "En cours",
    classGroup: "back",
  },
];
